#!/usr/bin/env python3
"""The regeneration defence rerun (2026-09-17) with the
benchmark's own vendor. Golds regenerated by gemini-3-flash-preview
(results/defense_eval_gemini/eval_<set>_<model>.json, data built by
scripts/defense_regen_gemini.slurm) beside the Qwen3-32B-AWQ run
(results/defense_eval/): easy-tier R@1/5/10 per model and set, the
D1-minus-verified gap, the judge acceptance counts from both manifests, and a
query-gold word-token Jaccard (lowercased letter and digit runs) per version on
the queries both accepted slices share. Writes results/defense_gemini_summary.json."""
import json, os, re, statistics as st
P = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SETS = ["orig", "exact", "paraphrase", "style", "mixed"]
MODELS = ["base", "ctrl-cas", "d1-ctrl-llm", "d2-paraphrase", "d3-style", "d4-unrelated"]
RUNS = (("qwen", "defense_eval"), ("gemini", "defense_eval_gemini"))


def jl(p):
    return [json.loads(l) for l in open(p, encoding="utf-8")]


def qrels(p):
    d = {}
    with open(p, encoding="utf-8") as f:
        next(f)
        for line in f:
            q, doc, s = line.rstrip("\n").split("\t")
            if int(s) > 0:
                d.setdefault(q, []).append(doc)
    return d


tok = lambda t: set(re.findall(r"[a-z]+|\d+", t.lower()))
out = {}
for gen, d in RUNS:
    out[gen] = {"eval_dir": f"results/{d}", "sets": {}}
    for s in SETS:
        row = {}
        for m in MODELS:
            f = f"{P}/results/{d}/eval_{s}_{m}.json"
            row[m] = json.load(open(f))["overall"] if os.path.exists(f) else None
        row["gap_d1_minus_verified"] = (round(row["d1-ctrl-llm"]["recall@1"] - row["ctrl-cas"]["recall@1"], 2)
                                        if row["d1-ctrl-llm"] and row["ctrl-cas"] else None)
        out[gen]["sets"][s] = row
    bs = f"{P}/data/{d}/build_summary.json"
    if os.path.exists(bs):
        out[gen]["shared_slice"] = json.load(open(bs)).get("shared_slice")
    man = json.load(open(f"{P}/data/{d}/regen_manifest.json"))
    out[gen]["generator"] = {k: man["config"].get(k) for k in ("model", "backend", "judge_backend", "judge_model", "n_queries", "seed")}
    out[gen]["judge"] = {v: {"candidates": sum(1 for e in man["queries"].values() if e.get(v, {}).get("text")),
                             "verified": sum(1 for e in man["queries"].values() if e.get(v, {}).get("verified"))}
                         for v in ("exact", "paraphrase", "style")}
# query-gold token overlap on the queries both accepted slices share
slices = {gen: {q["_id"] for q in jl(f"{P}/data/{d}/orig/queries.jsonl")} for gen, d in RUNS}
common = sorted(slices["qwen"] & slices["gemini"])
out["overlap"] = {"definition": "Jaccard of lowercased letter/digit token sets, query vs its gold; mean over the queries in both accepted slices",
                  "n_queries": len(common), "by_run": {}}
for gen, d in RUNS:
    out["overlap"]["by_run"][gen] = {}
    for s in ("orig", "exact", "paraphrase", "style"):
        q = {x["_id"]: x["text"] for x in jl(f"{P}/data/{d}/{s}/queries.jsonl")}
        qr = qrels(f"{P}/data/{d}/{s}/qrels/test.tsv")
        c = {x["_id"]: x["text"] for x in jl(f"{P}/data/{d}/{s}/corpus.jsonl")}
        js, ln = [], []
        for qid in common:
            g = qr[qid][0]; a, b = tok(q[qid]), tok(c[g])
            js.append(len(a & b) / max(1, len(a | b))); ln.append(len(c[g]))
        out["overlap"]["by_run"][gen][s] = {"jaccard_mean": round(st.mean(js), 3), "jaccard_median": round(st.median(js), 3),
                                            "gold_chars_mean": round(st.mean(ln), 1)}
json.dump(out, open(f"{P}/results/defense_gemini_summary.json", "w"), indent=2)
for gen, _ in RUNS:
    g = out[gen]
    print(f"== {gen} ({g['generator']['model']}; shared slice {g.get('shared_slice')}; judge " +
          ", ".join(f"{v} {j['verified']}/{j['candidates']}" for v, j in g["judge"].items()) + ")")
    for s in SETS:
        r = g["sets"][s]
        print(f"  {s:10s} " + " ".join(f"{m}={r[m]['recall@1']}/{r[m]['recall@5']}/{r[m]['recall@10']}" for m in MODELS) + f"  gap={r['gap_d1_minus_verified']}")
print(f"== overlap on {out['overlap']['n_queries']} shared queries")
for gen, v in out["overlap"]["by_run"].items():
    print("  " + gen + "  " + "  ".join(f"{s}={r['jaccard_mean']}" for s, r in v.items()))
