#!/usr/bin/env python3
"""
Emit paper/dose_prompts.tex: every generation prompt the paper's attacks ran,
verbatim, plus a quantified lexical distance between the four ladder rungs.

Generated FROM the scripts that ran rather than pasted, so the paper cannot
drift from the prompts:
  * scripts/generate_llm_pairs.py   D1-D4 rewriter prompts, D5 (survey author),
                                    the unrelated near-misses prompt, every user
                                    message, and the judge that filters pairs;
  * scripts/generate_meld_pairs.py  the reconstructed MELD generation prompt,
                                    the rewritten prompt of the 84/16 control,
                                    and the validity/equivalence screen;
  * data/saber/upstream_ref/prompts.py  SABER's own solution-summary prompt,
                                    used byte for byte.
D1 is MathNet-Retrieve's own published Appendix-F rewriter prompt (public in
arXiv:2604.18584v2), adapted near-verbatim with only the output format bound
to our strict-JSON schema.

Usage:  python scripts/dump_dose_prompts.py
"""

import importlib.util
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "paper", "dose_prompts.tex")

RUNGS = [
    ("D1", "the benchmark's own Appendix-F template (the recipe arm)", "GEN_SYSTEM", "GEN_USER"),
    ("D2", "a close paraphrase of that template", "GEN_SYSTEM_PARAPHRASE", "GEN_USER_PARAPHRASE"),
    ("D3", "a rewriter prompt in a deliberately different style", "GEN_SYSTEM_STYLE", "GEN_USER_STYLE"),
    ("D4", "a restatement prompt unrelated to the recipe", "GEN_SYSTEM_UNRELATED", "GEN_USER_UNRELATED"),
]


def load_module(name, relpath):
    path = os.path.join(ROOT, *relpath.split("/"))
    sys.path.insert(0, os.path.dirname(path))
    spec = importlib.util.spec_from_file_location(name, path)
    m = importlib.util.module_from_spec(spec)
    sys.modules[name] = m
    try:
        spec.loader.exec_module(m)
    except SystemExit:
        pass
    return m


def words(s):
    return set(re.findall(r"[a-z]+", s.lower()))


def verbatim(L, text):
    # fvextra's Verbatim, NOT plain verbatim: the source prompts contain
    # lines up to 1,331 characters and plain verbatim does not wrap, so
    # everything past the right margin is dropped from the PDF entirely.
    L.append("\\begin{Verbatim}[breaklines=true,breakanywhere=true,fontsize=\\small]")
    L.append(text.strip())
    L.append("\\end{Verbatim}")
    L.append("")


def main():
    g = load_module("genllm", "scripts/generate_llm_pairs.py")
    meld = load_module("genmeld", "scripts/generate_meld_pairs.py")
    saber = load_module("saberprompts", "data/saber/upstream_ref/prompts.py")

    texts = {tag: getattr(g, attr) for tag, _, attr, _ in RUNGS}
    users = {tag: getattr(g, uattr) for tag, _, _, uattr in RUNGS}
    d1 = words(texts["D1"])
    jac = {t: len(d1 & words(s)) / len(d1 | words(s)) for t, s in texts.items()}
    saber_summary = saber.extract_core_idea_query("{statement}", "{solution}")

    L = []
    L.append("% GENERATED by scripts/dump_dose_prompts.py -- do not hand-edit.")
    L.append("% Sources of truth: scripts/generate_llm_pairs.py, scripts/generate_meld_pairs.py,")
    L.append("% data/saber/upstream_ref/prompts.py (the prompts that ran).")
    L.append("\\section{The prompts, verbatim}")
    L.append("\\label{app:prompts}")
    L.append("")
    L.append("This appendix prints every prompt behind the paper's attacks word for word, so that a "
             "reader can judge how far apart they are rather than take our labels for it. First the "
             "four rungs of the ladder of Section~\\ref{sec:mechanism}, which change one thing between "
             "rungs, the system prompt given to Qwen3-32B-AWQ, while the judge, the source problems and "
             "the training settings stay the same; each rung's user message carries only the source "
             "problem under a one-line header, and is printed beneath its system prompt. D1--D3 share one "
             "output format (D4 asks for restatements only and writes no negatives by design). D1 is "
             "MathNet-Retrieve's own published Appendix-F rewriter prompt, changed only so that its "
             "output matches our JSON format. Then the two further controls of Appendix~\\ref{app:mechanism}, "
             "the survey-author prompt D5 and the unrelated near-misses prompt, the judge that filters "
             "every LLM-written pair, and the prompts of the MELD and SABER-Math attacks of "
             "Section~\\ref{sec:ood}. Braces mark the slots the scripts fill.")
    L.append("")
    L.append("\\paragraph{Word overlap as a distance, and why we do not use it.}")
    L.append("One could measure the distance between prompts by how many words they share. The "
             "Jaccard similarity of word sets to D1 is " +
             ", ".join(f"{t} $= {jac[t]:.3f}$" for t, _, _, _ in RUNGS if t != "D1") +
             ", which does not follow the ladder's order: D4 shares more words with D1 than D3 "
             "does, yet D4 is the rung whose hard-tier score collapses, because it asks for a "
             "different task (restating a problem for another audience) and attaches no negatives. "
             "The factorial of Table~\\ref{tab:factorial} shows the collapse comes from the missing "
             "negatives ($10.30$ hard R@1 over eight seeds once the verified arm's counterexamples are "
             "attached, $26.97$ with the recipe arm's own near-misses). Word overlap is therefore the "
             "wrong measure of prompt distance, and the hard-tier ordering of "
             "Table~\\ref{tab:dose-full} does not follow it.")
    L.append("")
    for tag, desc, _, _ in RUNGS:
        L.append(f"\\paragraph{{{tag}: {desc}.}}")
        verbatim(L, texts[tag])
        L.append(f"User message of {tag}:")
        verbatim(L, users[tag])

    L.append("\\paragraph{D5: the survey-author prompt, the second recipe-free reference.}")
    L.append("A restatement prompt whose task framing is not an audience change: the model writes the "
             "problem as a survey author would present another author's problem. Like D4 it asks for "
             "restatements only.")
    verbatim(L, g.GEN_SYSTEM_SURVEY)
    L.append("User message of D5:")
    verbatim(L, g.GEN_USER_SURVEY)

    L.append("\\paragraph{The unrelated near-misses prompt.}")
    L.append("D4's restatement task with a second step that writes minimal-edit companions, so that "
             "near-misses can be produced by a prompt that shares nothing with the recipe.")
    verbatim(L, g.GEN_SYSTEM_UNRELATED_NEGS)
    L.append("User message:")
    verbatim(L, g.GEN_USER_UNRELATED_NEGS)

    L.append("\\paragraph{The judge that keeps or drops every LLM-written pair.}")
    L.append("Ours, since the benchmark does not print its judge prompt; run through Qwen3-32B-AWQ, "
             "and for the two-judge control of Appendix~\\ref{app:mechanism} through "
             "Mistral-Small-24B-Instruct-2501 as well.")
    verbatim(L, g.JUDGE_SYSTEM)
    L.append("User message of the judge:")
    verbatim(L, g.JUDGE_USER)

    L.append("\\paragraph{The MELD attack: the reconstructed generation prompt.}")
    L.append("MELD publishes the prompts of its training pipeline but not the one behind its "
             "evaluation set; this is our reconstruction of the procedure its paper describes, into "
             "the schema of its released records. The connection descriptions per subfield pair are ours.")
    verbatim(L, meld.MELD_GEN_SYSTEM)
    L.append("User message (first call per subfield pair):")
    verbatim(L, meld.MELD_GEN_USER)
    L.append("User message (later calls, which pass back the topics already produced):")
    verbatim(L, meld.MELD_GEN_USER_CONT)

    L.append("\\paragraph{The MELD attack: the rewritten prompt of the $84/16$ control.}")
    verbatim(L, meld.MELD_GEN_SYSTEM_ALT)

    L.append("\\paragraph{The MELD attack: the validity and equivalence screen.}")
    L.append("MELD's three-question check, run through Qwen3-32B-AWQ; we gate on validity and "
             "equivalence and only record the dissimilarity answer.")
    verbatim(L, meld.MELD_JUDGE_SYSTEM)
    L.append("User message of the screen:")
    verbatim(L, meld.MELD_JUDGE_USER)

    L.append("\\paragraph{The SABER-Math attack: SABER's own solution-summary prompt.}")
    L.append("Taken byte for byte from SABER's repository (\\texttt{annotate/ideas/prompts.py}) and run "
             "through Qwen3-32B-AWQ in place of GPT-OSS-120B; the summaries it writes are the only text "
             "the attack trains on.")
    verbatim(L, saber_summary)

    with open(OUT, "w", encoding="utf-8") as f:
        f.write("\n".join(L) + "\n")
    print(f"wrote {OUT}")
    for t, _, _, _ in RUNGS:
        print(f"  {t}: {len(texts[t])} chars, jaccard-to-D1 {jac[t]:.3f}")


if __name__ == "__main__":
    main()
